# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e460ce35b2d2a1678fb3d69617afdcc3b3efb12e998751d349479738f201c6e80eddde35229634b0665b9a8a40597dc0e1e018564e48a65f7e8262b65f44e08

test:
  secret_key_base: 0fbc3f1241485c29c8c77c61e66c16dc7826937d3b4513717e435ca32f5ca3c7e2753a125846d72299b5ce14bb6cf50469c4b75d26f170046fbfbfa1f0ec377c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
